server:
    port: 8999
spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost/spring-cloud-learn?useUnicode=true&characterEncoding=utf-8
        username: dev
        password: dev
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 1
        minIdle: 1
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat
mybatis:
    config-location: classpath:sqlMapConfig.xml
    mapper-locations: classpath*:com/cr6588/dao/mapper/*.xml
logging:
    config: classpath:logback-dev.xml
#dubbo:
#    scan:
#        basePackages: com.cr6588.service.impl
#    application:
#        name: provider
 #   registry:
 #       protocol: zookeeper
 #       address: localhost:2181
#    protocol: 
#        name: dubbo
#        port: 21001

