debug: false
server:
    port: 8080
logging:
    config: classpath:logback-dev.xml
dubbo:
    application:
        name: consumer
    registry:
        protocol: zookeeper
        address: zookeeper.cr6588.com:2181
#    protocol: 
#        name: dubbo
#        port: 31001
    consumer: 
        timeout: 30000
        retries: 0
        false: false
#spring:
#https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/reference/htmlsingle/#howto-spring-mvc
#org.springframework.boot.autoconfigure.web.WebMvcProperties
#    mvc:
#        view:
#            prefix: /WEB-INF/jsp/
#            suffix: .jsp
